mysite/blogging/urls.py
from django.urls import path
from blogging.views import PostListView, PostDetailView, PostAddView

urlpatterns = [
    path("", PostListView.as_view(), name="blog_index"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="blog_detail"),
    path("add/", PostAddView.as_view(), name="add_post"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    path("", include("blogging.urls")),
    path("admin/", admin.site.urls),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("polling/", include("polling.urls")),
    path("register/", views.register_request, name="register"),
]

mysite/polling/urls.py
from django.urls import path
from polling.views import PollListView, PollDetailView

urlpatterns = [
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
]

mysite/blogging/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("/")


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

mysite/polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

mysite/mysite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

mysite/blogging/views.py
from datetime import datetime
from django.shortcuts import render
from django.template import loader
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from blogging.models import Post


class PostListView(ListView):
    context_object_name = "post_list"
    queryset = Post.objects.exclude(published_date__exact=None).order_by(
        "-published_date"
    )
    template_name = "blogging/list.html"


class PostDetailView(DetailView):
    context_object_name = "post_detail"
    queryset = Post.objects.exclude(published_date__exact=None)
    template_name = "blogging/detail.html"


class PostAddView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "blogging/add.html"
    fields = ["title", "text"]
    success_url = reverse_lazy("blog_index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.published_date = datetime.now()
        return super().form_valid(form)

mysite/mysite/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login
from django.contrib import messages


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful. ")
            return redirect("/")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(
        request=request, template_name="register.html", context={"register_form": form}
    )

mysite/polling/views.py
from django.shortcuts import render
from django.http import Http404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from polling.models import Poll


class PollListView(ListView):
    model = Poll
    template_name = "polling/list.html"


class PollDetailView(DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()

        context = {"object": poll}
        return render(request, "polling/detail.html", context)

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Django Blog</title>
    <link type="text/css" rel="stylesheet" href="{% static 'django_blog.css' %}">
  </head>
  <body>
    <div id="header">
      <ul id="control-bar">
        {% if user.is_authenticated %}
          {% if user.is_staff %}
          <li><a href="{% url 'admin:index' %}">admin</a></li>{% endif %}
          <li><a href="{% url 'add_post' %}">add post</a></li>
          <li><a href="{% url 'logout' %}">logout</a></li>
        {% else %}
        <li><a href="{% url 'register' %}">register</a></li>
          <li><a href="{% url 'login' %}">login</a></li>
        {% endif %}
      </ul>
    </div>
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

mysite/templates/blogging/add.html
{% extends "base.html" %}
{% block content %}
<h1>Add Post</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>POST</button>
</form>

{% endblock %}

mysite/templates/blogging/detail.html
{% extends "base.html" %}
{% block content %}
<a class="backlink" href="/">Home</a>
<h1>{{ object.title }}</h1>
<p class="byline">
    Posted by: {{ object.author.username }} &mdash; {{ object.published_date }}
</p>
<div class="post-body">
    {{ object.text }}
</div>
<br/>
<ul class="categories">
    {% for category in object.categories.all %}
    <li>{{ category }}</li>
    {% endfor %}
</ul>
{% endblock %}

mysite/templates/blogging/list.html
{% extends "base.html" %}
{% block content %}
<h1>Blog Posts</h1>
{% for post in post_list %}
    <div class="post">
        <h2>
            <a href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a>
        </h2>
        <p class="byline">
            Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
        </p>
        <div class="post-body">
            {{ post.text|truncatechars:40 }}...
        </div>
        <ul class="categories">
            {% for category in post.categories.all %}
            <li>{{ category }}</li>
            {% endfor %}
        </ul>
    </div>
{% endfor %}
{% endblock %}

mysite/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>My Blog Login</h1>
<form action="" method="POST">{% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Log In"></p>
</form>
{% endblock %}

mysite/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<div class="poll-body">
    {{ object.text }}
</div>
<div class="poll-score">
    Current score: {{ object.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

mysite/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}

mysite/templates/register.html
{% extends "base.html" %}
{% block content %}
<h1>Register</h1>

<form method="POST">
    {% csrf_token %}
    {{ register_form.as_p }}
    <button type="submit">Register</button>
</form>
<p>If you already have an account, <a href="{% url 'login' %}">login</a> instead.</p>

{% endblock %}